// =============================================
// ARCHIVO: src/tutoriales.js
// Contenido de los tutoriales del sistema (uno por módulo/sección).
// Se muestra en el menú "📚 Tutoriales". El contenido está separado de la vista:
// Tutoriales.jsx arma las tarjetas y VisorTutorial.jsx muestra el detalle.
//
// Estructura de cada tutorial:
//   id, icono, titulo, resumen, color, gating {siempre|permiso|rolAdmin|funcion}, pro?
//   intro                → para qué sirve (simple)
//   beneficios: [ ... ]  → "Para qué te sirve" (ventajas)
//   pasos: [{titulo,texto,imagen?}]        → cómo se usa (paso a paso)
//   funciones: [ '<encabezado>' | {titulo,texto} ]  → CADA botón/opción explicado
//   tips: [ ... ]  ·  erroresComunes: [ ... ]
// Imágenes: frontend/public/tutoriales/*.png → '/tutoriales/archivo.png' (se ocultan si faltan).
// =============================================

export const TUTORIALES = [
  {
    id: 'pos',
    icono: '🛒',
    titulo: 'Punto de Venta',
    resumen: 'El corazón del negocio: vender y cobrar.',
    color: 'from-emerald-500 to-green-600',
    gating: { siempre: true },
    intro: 'El Punto de Venta (POS) es la pantalla donde vendés. Buscás lo que lleva el cliente, el sistema suma solo, calcula el vuelto y, si querés, hace la factura. Entrás desde el botón "🛒 Punto de Venta" arriba del menú.',
    beneficios: [
      'Vendés rapidísimo: escribís o escaneás y listo.',
      'Calcula el total y el vuelto solo, sin errores al dar el cambio.',
      'Descuenta el stock automáticamente en cada venta.',
      'Aceptás efectivo, tarjeta, transferencia, Mercado Pago, pago dividido y fiado.',
      'Atendés a varios clientes a la vez con pestañas de venta.',
      'Funciona sin internet: guarda las ventas y las sube solas al reconectar.',
      'Si tenés facturación, emitís la factura oficial en el mismo cobro.',
    ],
    pasos: [
      { titulo: 'Abrí tu caja', texto: 'Elegí tu caja (mañana, tarde, etc.) y tocá para abrirla o unirte. Sin caja abierta no podés cobrar en efectivo.', imagen: '/tutoriales/pos-1.png' },
      { titulo: 'Buscá el producto', texto: 'Escribí el nombre o código en el buscador, o escaneá el código de barras.', imagen: '/tutoriales/pos-2.png' },
      { titulo: 'Agregalo al carrito', texto: 'Tocá el producto para sumarlo. Ajustá la cantidad con + / − o tocando el número.' },
      { titulo: 'Cobrá', texto: 'Tocá "Confirmar Venta", elegí el medio de pago y, si es efectivo, poné con cuánto paga para ver el vuelto.' },
      { titulo: '(Si querés) Facturá', texto: 'Con la facturación activa, emitís la factura en el mismo cobro eligiendo el tipo de comprobante.' },
    ],
    funciones: [
      'Avisos que aparecen solos arriba',
      { titulo: 'Banner "Falta X min para el fin del día"', texto: 'Aparece cuando falta poco para el cierre del día (si el admin activó el aviso). El botón "Cerrar caja" abre el cierre.' },
      { titulo: 'Banner "Esta caja se pasó del horario"', texto: 'Aparece cuando ya pasó la hora de fin del día y la política es seguir vendiendo. Conviene cerrar la caja.' },
      { titulo: 'Banner rojo "SIN INTERNET — Modo Offline"', texto: 'No hay conexión: las ventas se guardan en el equipo y se suben solas al volver internet. Muestra cuántas quedan pendientes.' },
      { titulo: 'Banner "Sincronizando..." / "Ventas sincronizadas"', texto: 'Cuando vuelve internet, sube las ventas guardadas y avisa cuando terminó.' },
      { titulo: 'Pantalla "El día cerró"', texto: 'Bloquea la caja cuando pasó el horario y la política es "forzar cierre". Botones: cerrar la caja ahora, o cerrar sesión para que entre otro.' },
      'Barra de arriba (accesos rápidos)',
      { titulo: '"⚡ Rápida [F1]"', texto: 'Cobrar algo que no está en el inventario (propina, bolsa). Solo si el admin la activó.' },
      { titulo: '"🏷️ Alta rápida [F7]"', texto: 'Dar de alta un producto nuevo al toque; queda "por revisar" para completar después.' },
      { titulo: '"🔁 Movimientos"', texto: 'Enviar mercadería a otro de tus negocios (solo si tenés multinegocio activado).' },
      { titulo: '"👥 Fiados [F3]"', texto: 'Cobrar deudas o agregar deuda a un cliente de cuenta corriente.' },
      { titulo: '"📋 Historial [F5]"', texto: 'Ver las ventas del turno actual (se actualiza cada 5 segundos).' },
      { titulo: '"💸 Gastos [F10]"', texto: 'Registrar un gasto del turno o del local sin salir del POS.' },
      { titulo: '"🔒 Cierre [F4]"', texto: 'Cerrar la caja y hacer el arqueo (cuadrar el efectivo) al terminar el turno.' },
      { titulo: '"⚙️ Admin"', texto: 'Salir del POS y entrar al panel de administración.' },
      { titulo: '"☰" (en celular)', texto: 'Menú con todas esas acciones + "Actualizar app" (borra el caché y recarga).' },
      { titulo: 'Botón de la caja "⇄"', texto: 'Cambiar de caja SIN cerrarla (la caja queda abierta para los demás).' },
      { titulo: '"☀️/🌙"', texto: 'Modo claro u oscuro, solo en este equipo.' },
      { titulo: '"🔄"', texto: 'Fuerza actualizar la pantalla si algo quedó trabado.' },
      { titulo: '"👤"', texto: 'Cambiar de usuario (cambio de turno): cierra la sesión para que entre otro.' },
      'Buscador y lista de productos (izquierda)',
      { titulo: 'Buscador "🔍 ... [F2]"', texto: 'Escribí el nombre o escaneá el código. Si hay un solo resultado, lo agrega solo.' },
      { titulo: 'Orden "🎯 / A-Z / $↑ / $↓"', texto: 'Ordena los resultados por relevancia, alfabético, o precio de menor a mayor / mayor a menor.' },
      { titulo: 'Cartelito de stock en cada producto', texto: 'Verde = hay stock, ámbar = poco, rojo = sin stock. Solo se ve si el admin lo activó.' },
      { titulo: 'Productos por peso (kg/lt/mt)', texto: 'Al tocarlos abren la ventana "Vender por peso" para poner cantidad o precio.' },
      'Carrito (derecha) y pestañas',
      { titulo: 'Pestañas "Venta 1, Venta 2..."', texto: 'Varias ventas a la vez (un cliente por pestaña). Cada una guarda su carrito y sus descuentos.' },
      { titulo: '"+" y "✕" de pestañas', texto: '"+" abre una venta nueva; "✕" cierra esa pestaña.' },
      { titulo: 'Botones − / número / + de cada ítem', texto: 'Restar, escribir la cantidad exacta (tocando el número), o sumar una unidad.' },
      { titulo: '"%" en un producto', texto: 'Aplica descuento, recargo o redondeo SOLO a ese producto (si el admin lo configuró).' },
      { titulo: '"✕" rojo del ítem', texto: 'Saca ese producto del carrito.' },
      { titulo: '"✕ Limpiar"', texto: 'Vacía todo el carrito de la venta activa.' },
      { titulo: 'Descuento / "+ Rec %" / "↓ Bajar" / "↑ Subir"', texto: 'Aplican descuento, recargo o redondeo a TODA la venta (según lo que configuró el admin).' },
      { titulo: '"✅ Confirmar Venta [F8]"', texto: 'Abre el cobro. Se desactiva si el carrito está vacío.' },
      'Atajos de teclado',
      { titulo: 'F1..F10, Esc y escáner', texto: 'F1 venta rápida · F2 buscador · F3 fiados · F4 cierre · F5 historial · F7 alta rápida · F8 confirmar · F9 limpiar · F10 gastos · Esc cierra ventanas. El escáner agrega el producto por su código.' },
      'Ventana: Apertura de caja',
      { titulo: 'Lista de cajas del local', texto: 'Elegís tu caja: 🔓 abierta (te unís) o 🔒 cerrada (la abrís con el efectivo inicial).' },
      { titulo: '"Efectivo inicial en caja"', texto: 'La plata con la que arrancás; viene precargada con lo que dejó la caja anterior.' },
      { titulo: '"➕ Caja provisoria / eventual"', texto: 'Abrir una caja temporal (evento, delivery) cuando ya se usaron las fijas.' },
      'Ventana: Confirmar Venta (cobro)',
      { titulo: 'Medios de pago', texto: 'Efectivo, Tarjeta, Mercado Pago, Transferencia, Cuenta Corriente y Pago dividido (efectivo + virtual). Solo aparecen los que activó el admin.' },
      { titulo: '"Efectivo entregado" y "Vuelto"', texto: 'Ponés con cuánto paga y calcula el vuelto (rojo si falta).' },
      { titulo: 'Cuenta corriente', texto: 'Buscás al cliente (o creás uno nuevo) y la venta se suma a su deuda.' },
      { titulo: 'Facturación Electrónica (si está activa)', texto: 'Botón para emitir factura válida ante ARCA, con tipo de comprobante, tipo/nº de documento y datos del cliente.' },
      'Otras ventanas',
      { titulo: 'Venta Exitosa', texto: 'Tras cobrar: "Seguir vendiendo [F8]" e "Imprimir ticket" o "Ver Comprobante Electrónico".' },
      { titulo: 'Cierre de Caja (F4)', texto: 'Arqueo del turno: contar billetes, efectivo a retirar y para el próximo turno, y declarar tarjetas/MP/transferencias. Muestra si cuadra o hay diferencia.' },
      { titulo: 'Contar Billetes (F12)', texto: 'Cargás cuántos billetes de cada valor tenés y calcula el total contado.' },
    ],
    tips: [
      'El lector de código funciona como si escribieras: parate en el buscador y escaneá.',
      'Las pestañas te dejan tener varias ventas abiertas al mismo tiempo.',
      'Al terminar el día, cerrá la caja (F4) para el arqueo.',
    ],
    erroresComunes: [
      'Si no te deja cobrar en efectivo, la caja no está abierta.',
      'Si un producto no aparece, fijate que esté activo y con stock (o activá "vender sin stock").',
      'En modo sin internet, el ticket recién se puede imprimir cuando la venta se sincroniza.',
    ],
  },
  {
    id: 'dashboard',
    icono: '📊',
    titulo: 'Dashboard (Inicio)',
    resumen: 'Cómo va tu negocio, de un vistazo.',
    color: 'from-sky-500 to-blue-600',
    gating: { permiso: 'dashboard' },
    intro: 'El Dashboard es la pantalla de inicio: la foto del día de tu negocio (ventas, medios de pago, gastos y ganancia) en tarjetas grandes y fáciles de leer.',
    beneficios: [
      'En 5 segundos sabés cómo viene el día y el mes.',
      'Ves cuánto entró por cada medio de pago.',
      'Muestra la ganancia real (venta − costo − IVA − gastos), no solo lo que entró.',
      'Te avisa lo importante: stock bajo, deudas, gastos del día.',
      'Las tarjetas son botones: tocás una y vas al detalle.',
    ],
    pasos: [
      { titulo: 'Mirá el resumen del día', texto: 'Total vendido hoy, cantidad de ventas y ticket promedio. Se actualiza solo.', imagen: '/tutoriales/dashboard-1.png' },
      { titulo: 'Fijate por dónde entra la plata', texto: 'Tarjetas de efectivo, transferencias, tarjetas y Mercado Pago con su monto y porcentaje.' },
      { titulo: 'Controlá el mes', texto: 'Ventas del mes, gastos del mes y ganancia neta real.' },
      { titulo: 'Tocá una tarjeta para el detalle', texto: 'Te lleva a la sección relacionada (reportes, gastos, deudas, etc.).' },
    ],
    funciones: [
      'Arriba',
      { titulo: '"🎯 Centro de Control"', texto: 'Va a la pantalla de ganancia real, dinero disponible y control avanzado.' },
      { titulo: '"🔄 Actualizar"', texto: 'Recarga los datos a mano (además se actualizan solos cada 5 minutos).' },
      { titulo: '"⚡ Hoy" y selector de fecha', texto: 'Podés ver el resumen de un día pasado; "Hoy" vuelve al día actual. No deja elegir días futuros.' },
      'Resumen del día',
      { titulo: 'Tarjetas de medios de pago', texto: 'Efectivo, Transferencias, Tarjetas y Mercado Pago: monto, ventas y % del total. Al tocarlas abren el detalle de esas ventas.' },
      { titulo: 'Tarjeta "🧾 Facturación (ARCA)"', texto: 'Cuántas ventas se facturaron y el monto (si tenés facturación activa). Se toca para ver el detalle.' },
      { titulo: 'Tarjeta "💸 Gastos del día"', texto: 'Total gastado hoy y de dónde salió (caja / local / MP).' },
      { titulo: '"🕒 Ventas por hora" y "🏆 Lo más vendido"', texto: 'Gráfico de ventas por hora y ranking de productos del día.' },
      'Tarjetas del mes (llevan a otra sección)',
      { titulo: '"Ventas del mes" → Reportes', texto: 'Monto facturado y cantidad de ventas del mes.' },
      { titulo: '"Gastos del mes" → Gastos', texto: 'Egresos del mes.' },
      { titulo: '"Ganancia neta real" → Centro de Control', texto: 'Ganancia real (venta − costo − IVA − gastos de caja).' },
      { titulo: '"Deudas totales" → Cuentas Corrientes', texto: 'Total que te deben los clientes.' },
      { titulo: '"Ayer", "Productos", "Stock bajo"', texto: 'Ayer carga el resumen de ayer; Productos lleva al catálogo; Stock bajo abre la lista de lo que hay que reponer.' },
      'Comparativas y gráficos',
      { titulo: 'Tendencias', texto: 'Últimos 7 días vs 7 previos, este mes vs el mes pasado, y proyección de fin de mes.' },
      { titulo: 'Gráfico "Análisis de Ventas"', texto: 'Elegís período (7D/30D/3M/6M/1A) y tipo (área/barras/línea).' },
      { titulo: 'Top productos y métodos de pago del mes', texto: 'Ranking con medallas y torta de medios de pago.' },
    ],
    tips: [
      'Miralo cada mañana para tomarle el pulso al negocio.',
      'Para que la "ganancia real" sea exacta, cargá bien costos y gastos.',
    ],
    erroresComunes: [
      'Si ves todo en cero, quizás no haya ventas cargadas en ese período.',
    ],
  },
  {
    id: 'productos',
    icono: '📦',
    titulo: 'Productos',
    resumen: 'Todo lo que vendés, cargado y ordenado.',
    color: 'from-violet-500 to-purple-600',
    gating: { permiso: 'productos' },
    intro: 'Productos es la lista de todo lo que vendés, con precio, costo, código y stock. Es la base del sistema: cuanto mejor cargados, más rápido vendés y mejor salen los números.',
    beneficios: [
      'Vender es más rápido: el producto ya tiene precio y código.',
      'Sabés cuánto ganás con cada cosa (si cargás el costo).',
      'Cambiás precios de a uno o de a muchos juntos.',
      'Cargás productos en masa desde Excel.',
      'Los organizás por categoría y con foto.',
      'Te marca los de poco stock para reponer a tiempo.',
    ],
    pasos: [
      { titulo: 'Creá un producto', texto: 'Tocá "+ Nuevo Producto", cargá nombre, precio y (recomendado) el costo.', imagen: '/tutoriales/productos-1.png' },
      { titulo: 'Ponele código y categoría', texto: 'Cargá el código de barras y elegí la categoría. Podés subir foto.' },
      { titulo: 'Cargá el stock', texto: 'Cuánto tenés y un stock mínimo para que te avise cuando baje.' },
      { titulo: 'Editá cuando cambie el precio', texto: 'Tocá el producto o "Editar". Con "Actualizar precios" cambiás varios a la vez.', imagen: '/tutoriales/productos-2.png' },
    ],
    funciones: [
      'Botones de arriba',
      { titulo: '"📋 Plantilla Excel"', texto: 'Descarga un Excel de ejemplo con las columnas correctas para cargar productos y después importarlos.' },
      { titulo: '"📥 Importar Excel"', texto: 'Cargá o actualizá muchos productos desde un Excel. Reconoce las columnas por su nombre e importa de a 300, avisando cuántos se crearon/actualizaron.' },
      { titulo: '"📊 Exportar Excel"', texto: 'Descarga TODOS los productos (según el filtro) a Excel para editarlos afuera y reimportarlos.' },
      { titulo: '"💲 Actualizar Precios"', texto: 'Cambio masivo de precios (por %, monto fijo o precio exacto), a todos, a una categoría o a los seleccionados.' },
      { titulo: '"+ Nuevo Producto"', texto: 'Crea un producto nuevo. En plan Estándar, si llegás al límite, avisa que necesitás Premium.' },
      'Filtros',
      { titulo: 'Buscador por nombre o código', texto: 'Filtra la lista a medida que escribís.' },
      { titulo: 'Selector de categoría', texto: 'Muestra solo los productos de esa categoría.' },
      { titulo: '"⚠️ Stock bajo"', texto: 'Muestra solo los productos en o por debajo del mínimo.' },
      { titulo: '"🏷️ Por revisar (N)"', texto: 'Muestra los productos cargados rápido desde el POS a los que les falta precio, costo o categoría.' },
      'Tabla de productos',
      { titulo: 'Edición rápida (clic en Precio o Stock)', texto: 'Tocá el precio o el stock para editarlo ahí mismo: Enter guarda, Escape cancela. Si cambiás el costo, recalcula el precio con el margen.' },
      { titulo: 'Ordenar por columna', texto: 'Tocá el encabezado (Código, Nombre, Costo, Venta, Stock) para ordenar; otra vez invierte el orden.' },
      { titulo: '"Editar"', texto: 'Abre el formulario completo del producto.' },
      { titulo: '"⧉" (duplicar)', texto: 'Crea una copia del producto (para variantes), con nombre "(copia)", sin código y stock 0.' },
      { titulo: '"Borrar"', texto: 'Desactiva el producto (con confirmación).' },
      { titulo: 'Selección múltiple (checkboxes)', texto: 'Al tildar varios aparecen acciones masivas: actualizar precios, eliminar, o mover a otra categoría.' },
      'Ventana: Nuevo / Editar producto',
      { titulo: '"📦 Normal" vs "🧩 Combinado"', texto: 'Producto común con stock propio, o combo armado con otros productos (el stock se calcula por el componente más escaso).' },
      { titulo: 'Nombre, código, categoría, unidad', texto: 'Datos básicos. Si dejás el código vacío, se genera uno interno. El "+" al lado de categoría crea una nueva al instante.' },
      { titulo: 'Precio costo, margen %, IVA %, precio final', texto: 'Cargando costo y margen, calcula solo el precio de venta (podés escribirlo a mano igual).' },
      { titulo: 'Stock y stock mínimo', texto: 'Cantidad actual y el número que dispara la alerta. Al editar, solo se cambia si lo tocás (no pisa lo que bajó por ventas).' },
      { titulo: 'Códigos de barras alternativos', texto: 'Al editar, podés agregar varios códigos al mismo producto (escaneando o escribiendo).' },
    ],
    tips: [
      'Cargar el costo es clave para ver la ganancia real.',
      'Con "Importar Excel" cargás todo el catálogo de una.',
      'El código de barras hace que vender sea instantáneo.',
    ],
    erroresComunes: [
      'Si un producto no aparece al vender, fijate que esté "activo".',
      'Usá el separador de decimales que muestra el campo para no equivocarte con el precio.',
    ],
  },
  {
    id: 'categorias',
    icono: '🏷️',
    titulo: 'Categorías',
    resumen: 'Ordenar los productos por rubro.',
    color: 'from-amber-500 to-orange-600',
    gating: { permiso: 'productos' },
    intro: 'Las categorías son como cajones para ordenar tus productos (Bebidas, Limpieza, Almacén...). Sirven para encontrar todo rápido y para ver qué rubro vende más.',
    beneficios: [
      'Encontrás los productos más rápido.',
      'Los reportes por categoría muestran qué rubro deja más plata.',
      'En el POS filtrás por categoría.',
      'Mantenés todo prolijo aunque tengas cientos de productos.',
    ],
    pasos: [
      { titulo: 'Creá una categoría', texto: 'Tocá "+ Nueva", ponele un nombre claro y guardá.', imagen: '/tutoriales/categorias-1.png' },
      { titulo: 'Asigná los productos', texto: 'Al crear o editar un producto, elegí su categoría.' },
    ],
    funciones: [
      'Arriba',
      { titulo: '"🔗 Unir"', texto: 'Junta dos categorías repetidas en una sola (mueve los productos y borra la duplicada).' },
      { titulo: '"+ Nueva"', texto: 'Crea una categoría (solo pide el nombre).' },
      { titulo: 'Aviso de repetidas', texto: 'Si detecta nombres duplicados, te avisa y ofrece unirlas.' },
      'En cada tarjeta de categoría',
      { titulo: '"👁️ Ver"', texto: 'Abre la lista de productos de esa categoría (solo lectura).' },
      { titulo: '"✏️" (renombrar)', texto: 'Cambia el nombre de la categoría.' },
      { titulo: '"🗑️" (eliminar)', texto: 'Borra la categoría. Solo se puede si no tiene productos.' },
    ],
    tips: [
      'Pocas categorías claras funcionan mejor que muchas específicas.',
    ],
    erroresComunes: [
      'Si borrás una categoría con productos, esos productos quedan sin categoría: reasignálos.',
    ],
  },
  {
    id: 'stock',
    icono: '📉',
    titulo: 'Stock',
    resumen: 'Saber cuánto tenés y reponer a tiempo.',
    color: 'from-rose-500 to-red-600',
    gating: { permiso: 'stock' },
    intro: 'Stock es el control de cuánto te queda de cada producto. Está pensado para usar con el celular caminando por el local: podés organizar los productos en secciones (góndolas, heladeras, depósito) igual que tus estanterías.',
    beneficios: [
      'Sabés en todo momento cuánto tenés de cada cosa.',
      'Te avisa cuáles están por agotarse.',
      'Cargás la mercadería que llega en un par de toques.',
      'Ajustás diferencias (roturas, faltantes) para que el número sea real.',
      'Organizás el inventario igual que tus estanterías para contar más rápido.',
    ],
    pasos: [
      { titulo: 'Revisá las existencias', texto: 'La lista muestra cuánto tenés; los bajos aparecen resaltados y arriba dice "X con stock bajo".', imagen: '/tutoriales/stock-1.png' },
      { titulo: 'Sumá lo que llega', texto: 'Con "📥 Agregar stock" sumás las cantidades recibidas.' },
      { titulo: 'Ajustá diferencias', texto: 'Con "Ajustar" corregís la cantidad contada de cada producto.' },
    ],
    funciones: [
      'Botones de arriba',
      { titulo: '"📥 Agregar stock"', texto: 'Recepción de mercadería: SUMA cantidades al stock (no lo reemplaza). Podés cargar varios productos a la vez.' },
      { titulo: '"📊 Vendidos por sección"', texto: 'Informe de lo vendido agrupado por tus secciones, en un rango de fechas; exporta a Excel.' },
      { titulo: '"📤 Exportar"', texto: 'Exporta el inventario (nombre y cantidad) a Excel o PDF, eligiendo qué secciones/productos.' },
      { titulo: '"✋ Organizar" / "✅ Listo"', texto: 'Activa el modo para arrastrar productos, moverlos de sección y ordenar las secciones. "➕ Sección" crea una nueva.' },
      'Buscador y filtros',
      { titulo: 'Buscador y filtro de categoría', texto: 'Buscás por nombre/código y filtrás por categoría.' },
      { titulo: 'Chip "⚠ N con stock bajo"', texto: 'Al tocarlo muestra solo los productos por debajo del mínimo.' },
      'En cada producto',
      { titulo: '"Ajustar"', texto: 'Abre un panel para escribir la cantidad contada (con − / número / +). En "Contar" recorre la sección producto por producto sin volver a la lista.' },
      { titulo: '"🕒" (historial de stock)', texto: 'Muestra los movimientos de stock: fecha, quién y el cambio (subió/bajó).' },
      { titulo: '"✏️" (modificar producto)', texto: 'Abre el mismo formulario completo de edición de Productos.' },
      { titulo: '"🗑️"', texto: 'Desactiva el producto (con confirmación).' },
      { titulo: 'Chip "🛒 N vend. hoy"', texto: 'Cuántos se vendieron hoy de ese producto (se actualiza solo).' },
    ],
    tips: [
      'Cargá la mercadería apenas llega para no vender algo que "no tenés".',
      'Poné stock mínimo a los productos importantes para que te avise.',
      'El modo "Contar" es ideal para hacer inventario caminando por el local.',
    ],
    erroresComunes: [
      'Si el stock no coincide, suele ser por ventas no registradas o compras sin cargar.',
    ],
  },
  {
    id: 'reportes',
    icono: '📈',
    titulo: 'Reportes',
    resumen: 'Ver cuánto vendiste y cuánto ganaste.',
    color: 'from-teal-500 to-emerald-600',
    gating: { permiso: 'reportes' },
    intro: 'Reportes es donde ves los números: cuánto vendiste, qué productos, por categoría, por medio de pago y tu ganancia. Podés mirar un día, una semana, un mes o el rango que quieras.',
    beneficios: [
      'Sabés exactamente cuánto vendiste en el período que elijas.',
      'Descubrís tus productos estrella (los que más venden y más dejan).',
      'Ves la ganancia real, no solo lo que entró.',
      'Comparás períodos para saber si crecés.',
      'Exportás todo a Excel o PDF.',
    ],
    pasos: [
      { titulo: 'Elegí el período', texto: 'Hoy, Por día, Por mes o Rango a medida. Todo se ajusta a eso.', imagen: '/tutoriales/reportes-1.png' },
      { titulo: 'Mirá los más vendidos', texto: 'El reporte por producto muestra qué se vendió más y cuánto dejó.' },
      { titulo: 'Exportá', texto: 'Con Excel o PDF te llevás la información.' },
    ],
    funciones: [
      'Pestañas',
      { titulo: '"📈 Historial"', texto: 'Las ventas del período con resúmenes, medios de pago y el detalle financiero.' },
      { titulo: '"📊 Reportes"', texto: 'Reportes especiales que se generan tocando una tarjeta (ver abajo).' },
      'Historial',
      { titulo: 'Filtros de período', texto: 'Hoy / Por día / Por mes / Rango. Se recarga solo al cambiarlos.' },
      { titulo: 'Tarjetas de resumen', texto: 'Total vendido, cantidad de ventas (con ticket promedio), efectivo y facturadas (ARCA), más transferencias, tarjetas y Mercado Pago.' },
      { titulo: 'Resumen financiero', texto: 'Ganancia neta real, ganancia en efectivo y virtual, IVA facturado, costo de lo vendido y gastos de caja.' },
      { titulo: 'Tabla "Detalle de Ventas"', texto: 'Cada venta con fecha, método, ítems y total. Tocá una fila para ver el detalle. Botones "📄 PDF" y "📊 Excel" para exportar.' },
      { titulo: 'Detalle de una venta', texto: 'Muestra los productos; podés reimprimir el ticket, anular la venta, y (si tiene factura) emitir Nota de Crédito.' },
      'Reportes especiales (tarjetas)',
      { titulo: '"🛒 Artículos Vendidos"', texto: 'Productos vendidos en el período, con cantidades y montos.' },
      { titulo: '"🔄 Reporte por Turno"', texto: 'Ventas, efectivo y gastos agrupados por cada turno trabajado.' },
      { titulo: '"💰 Rentabilidad"', texto: 'Ganancia y margen por producto y por categoría (margen bruto: venta − costo).' },
      { titulo: '"🏷️ Por Categoría"', texto: 'Ventas, unidades y ganancia de una categoría (elegís cuál y tocás "Filtrar").' },
      { titulo: '"📦 Stock Actual"', texto: 'Inventario completo con valor al costo y a la venta, y los de stock bajo resaltados.' },
      { titulo: 'Exportar PDF / Excel', texto: 'Cada reporte tiene sus botones para descargarlo.' },
    ],
    tips: [
      'Compará este mes con el anterior para ver si mejorás.',
      'La ganancia sale bien solo si los productos tienen su costo cargado.',
    ],
    erroresComunes: [
      'Si la ganancia se ve rara, casi siempre falta el costo en algunos productos.',
      'La "Rentabilidad" es margen bruto (no resta IVA ni gastos); la "Ganancia neta real" del Historial sí los resta. Por eso dan distinto.',
    ],
  },
  {
    id: 'caja',
    icono: '🏦',
    titulo: 'Control de Caja',
    resumen: 'Abrir, cerrar y controlar el efectivo.',
    color: 'from-lime-500 to-green-600',
    gating: { permiso: 'caja' },
    intro: 'Control de Caja es el historial y la configuración de tus cajas. Acá creás las cajas de tus turnos (Mañana, Tarde...), configurás el aviso de cierre y revisás los cierres de cada día. La caja se abre y se cierra desde el POS.',
    beneficios: [
      'Sabés siempre cuánta plata debería haber en cada caja.',
      'Detectás diferencias (faltantes o sobrantes) el mismo día.',
      'Cada turno queda separado y sabés quién trabajó.',
      'Manejás varias cajas sin mezclar la plata.',
    ],
    pasos: [
      { titulo: 'Creá tus cajas', texto: 'En "🏪 Cajas del local" escribí el nombre (ej. Mañana) y tocá "➕ Crear caja fija". Aparecerán siempre en el POS.' },
      { titulo: 'Configurá el aviso de cierre', texto: 'Activá "Avisar antes del fin del día" y elegí cuántos minutos antes.' },
      { titulo: 'Revisá los cierres', texto: 'Tocá un día en la lista para ver el cierre general y el detalle de cada caja.' },
    ],
    funciones: [
      'Cajas del local',
      { titulo: 'Lista de cajas + "×"', texto: 'Cada caja muestra 🔓/🔒. La "×" la elimina como opción (no borra el historial).' },
      { titulo: '"➕ Crear caja fija"', texto: 'Crea una caja nueva (ej. Mañana, Tarde, Trasnoche) que aparece al abrir caja en el POS.' },
      'Aviso de fin de día',
      { titulo: '"Avisar antes del fin del día"', texto: 'Activa un aviso en el POS antes de la medianoche; elegís cuántos minutos antes (5 a 120).' },
      { titulo: 'Qué pasa si sigue abierta', texto: '"Seguir normal" (sigue vendiendo, se marca fuera de hora) o "Forzar cierre" (no vende hasta cerrarla).' },
      'Historial',
      { titulo: 'Selector de mes', texto: 'Elegís qué mes ver.' },
      { titulo: 'Tarjetas del mes', texto: 'Ventas, gastos y ganancia neta del mes.' },
      { titulo: 'Lista "Cierres por día"', texto: 'Cada día resume todas sus cajas. Tocalo para abrir el cierre general del día.' },
      { titulo: 'Cierre general del día', texto: 'Totales del día, ventas por método y las cajas del día por horario; "Ver caja completa" abre el detalle de una.' },
      { titulo: 'Detalle de cierre (pestañas)', texto: '"Resumen" (totales), "Arqueo de caja" (esperado vs declarado y la diferencia), y "Gastos" del turno.' },
    ],
    tips: [
      'Cerrá la caja todos los días para detectar diferencias a tiempo.',
      'Registrá los retiros de efectivo apenas los hacés.',
    ],
    erroresComunes: [
      'Una diferencia grande casi siempre es un movimiento de efectivo no registrado.',
      'La caja se abre y cierra desde el POS; acá solo se consulta y se configura.',
    ],
  },
  {
    id: 'cuentas-corrientes',
    icono: '👥',
    titulo: 'Cuentas Corrientes',
    resumen: 'Los clientes que compran fiado.',
    color: 'from-cyan-500 to-sky-600',
    gating: { permiso: 'clientes' },
    intro: 'Acá manejás a los clientes que compran fiado: cuánto deben, su historial y los pagos. Se terminó el cuaderno: el sistema lleva la cuenta de cada uno.',
    beneficios: [
      'Sabés al instante cuánto te debe cada cliente.',
      'Tenés el historial completo: qué compró y qué pagó.',
      'Podés ponerle un límite de crédito.',
      'Cobrás pagos parciales o totales y el saldo se actualiza solo.',
    ],
    pasos: [
      { titulo: 'Creá el cliente', texto: 'Tocá "+ Nuevo Cliente" y cargá su nombre y teléfono.', imagen: '/tutoriales/cuentas-1.png' },
      { titulo: 'Vendé fiado', texto: 'En el POS, al cobrar, elegí "cuenta corriente" y el cliente. La compra se suma a su deuda.' },
      { titulo: 'Registrá el pago', texto: 'Con "💵 Cobrar" registrás lo que paga y el saldo baja solo.' },
    ],
    funciones: [
      'Arriba',
      { titulo: '"+ Nuevo Cliente"', texto: 'Alta de cliente: nombre (obligatorio), teléfono, email y dirección.' },
      { titulo: 'Tarjetas de resumen', texto: 'Deuda total, cuántos clientes deben y total de clientes.' },
      { titulo: 'Buscador', texto: 'Filtra por nombre o teléfono.' },
      'En cada cliente',
      { titulo: '"📊"', texto: 'Abre el historial completo de compras del cliente (con estadísticas y ranking de lo que más compra).' },
      { titulo: '"💵 Cobrar"', texto: 'Registra un pago. Tiene botones rápidos "50%" y "Pago Total", elección del medio de pago y una nota.' },
      { titulo: '"➕ Deuda"', texto: 'Agrega una deuda a mano (préstamo, artículo fuera de stock, fiado a mano).' },
      { titulo: '"🗑️" (en el detalle)', texto: 'Desactiva al cliente (con confirmación).' },
      'Detalle del cliente',
      { titulo: 'Deuda actual e historial', texto: 'Muestra el saldo y todos los movimientos: pagos (verde), deudas agregadas (ámbar) y ventas fiadas (rojo).' },
    ],
    tips: [
      'Revisá los saldos seguido para no acumular deuda incobrable.',
      'El límite de crédito te avisa cuando un cliente ya debe demasiado.',
    ],
    erroresComunes: [
      'Si un saldo no cierra, revisá que los pagos se hayan cargado en el cliente correcto.',
    ],
  },
  {
    id: 'proveedores',
    icono: '🚚',
    titulo: 'Proveedores',
    resumen: 'A quién le comprás y cuánto le debés.',
    color: 'from-indigo-500 to-violet-600',
    gating: { permiso: 'proveedores' },
    intro: 'En Proveedores registrás a quién le comprás, las compras y los pagos. Así sabés siempre cuánto le debés a cada uno (o cuánto te debe) y tenés el historial ordenado.',
    beneficios: [
      'Sabés cuánto le debés a cada proveedor, sin sorpresas.',
      'Tenés el historial de compras y pagos de cada uno.',
      'Te organizás para pagar en fecha.',
      'Podés adjuntar la boleta/comprobante de cada movimiento.',
    ],
    pasos: [
      { titulo: 'Cargá el proveedor', texto: 'Tocá "+ Nuevo Proveedor" y cargá nombre y teléfono.', imagen: '/tutoriales/proveedores-1.png' },
      { titulo: 'Registrá compras y pagos', texto: 'Las compras a crédito se cargan desde Gastos; los pagos, con "💵".' },
      { titulo: 'Mirá la ficha', texto: 'Entrá al proveedor para ver saldo, movimientos e historial.' },
    ],
    funciones: [
      'Arriba y vistas',
      { titulo: '"+ Nuevo Proveedor"', texto: 'Alta de proveedor (nombre y teléfono).' },
      { titulo: '"Activos" / "Archivados"', texto: 'Ves los proveedores en uso o los que archivaste (guardados fuera de la vista diaria).' },
      { titulo: '"🗂️ Tarjetas" / "📋 Lista"', texto: 'Cambia entre vista de tarjetas y de tabla.' },
      { titulo: '"Ordenar por"', texto: 'Alfabético, mayor deuda o mayor saldo a favor.' },
      { titulo: 'Tarjetas de resumen', texto: 'Cantidad de proveedores, cuánto "les debemos" y cuánto "nos deben".' },
      'En cada proveedor',
      { titulo: '"Ver ficha"', texto: 'Abre el detalle: saldos, movimientos recientes, gráfico de gastos por mes y notas.' },
      { titulo: '"✏️ Editar"', texto: 'Cambia nombre/teléfono y (solo si hubo un error) corrige los saldos a mano.' },
      { titulo: '"💵" (pago/cobro)', texto: 'Registra un pago (le pagás) o un cobro (te paga), con medio de pago, origen del dinero y opción de adjuntar boleta.' },
      'En la ficha',
      { titulo: '"Registrar pago / cobro"', texto: 'Salda deuda o registra lo que te pagan, con monto (botones "Total" y "50%").' },
      { titulo: '"Ver historial completo"', texto: 'Lista todos los movimientos (compras, gastos, pagos), con filtros por período y opción de editar o borrar cada uno.' },
      { titulo: '"📦 Archivar" / "♻️ Reactivar"', texto: 'Guarda el proveedor fuera de la vista diaria, o lo vuelve a activar.' },
      { titulo: '"🗑️ Eliminar"', texto: 'Borra el proveedor definitivamente (doble confirmación).' },
    ],
    tips: [
      'Tener el saldo al día evita pagar de más o dos veces.',
      'Las deudas se generan cargando compras a crédito desde Gastos, no a mano.',
    ],
    erroresComunes: [
      'Si el saldo no coincide, seguro falta cargar una compra o un pago.',
    ],
  },
  {
    id: 'gastos',
    icono: '💸',
    titulo: 'Gastos',
    resumen: 'Anotar lo que gastás para trabajar.',
    color: 'from-fuchsia-500 to-pink-600',
    gating: { permiso: 'gastos' },
    intro: 'En Gastos anotás todo lo que gastás para que el negocio funcione (alquiler, luz, sueldos, mercadería, fletes...). Es clave para saber la ganancia real. También registrás compras completas y pagos a proveedores.',
    beneficios: [
      'Sabés cuánto te cuesta tener el negocio abierto.',
      'La ganancia de los reportes se vuelve real (ventas − gastos).',
      'Ves en qué se te va la plata y podés recortar.',
      'Cargás compras con factura para el crédito de IVA.',
    ],
    pasos: [
      { titulo: 'Cargá un gasto', texto: 'Tocá "+ Nuevo Gasto", poné monto, descripción y de dónde sale el dinero.', imagen: '/tutoriales/gastos-1.png' },
      { titulo: 'Elegí el origen del dinero', texto: 'Caja del turno, dinero del local o Mercado Pago. Esto hace que la caja cierre bien.' },
      { titulo: 'Mirá el total', texto: 'El resumen y el libro diario te muestran en qué se te fue la plata.' },
    ],
    funciones: [
      'Arriba',
      { titulo: '"+ Nuevo Gasto"', texto: 'Abre el gasto rápido, con dos pestañas: "💸 Gasto" (gasto común) y "🧾 Pago a Proveedor".' },
      { titulo: '"📑 Gasto avanzado"', texto: 'Cargar una compra completa (boleta con productos, precios, IVA y proveedor).' },
      'Ventana Nuevo Gasto',
      { titulo: 'Monto, fecha, descripción, método', texto: 'Datos del gasto y cómo se pagó (efectivo, tarjeta, transferencia, MP).' },
      { titulo: '"¿De dónde sale el dinero?"', texto: '🧰 Caja del turno (descuenta del cierre), 🏪 Dinero del local, o 📱 MP del local. Importante para que la caja cuadre.' },
      { titulo: '"Gasto X" vs "🧾 Factura A"', texto: 'Sin comprobante fiscal, o con Factura A (suma el IVA como crédito al Resumen Fiscal).' },
      { titulo: 'Pestaña "Pago a Proveedor"', texto: 'Elegís proveedor, podés registrar una factura recibida y cuánto pagás ahora.' },
      'Gasto avanzado (compra)',
      { titulo: 'Datos de la compra', texto: 'Proveedor, tipo de comprobante (sin factura / A / B / C), condición IVA, número, método y estado de pago (total/parcial/deuda).' },
      { titulo: 'Productos de la compra', texto: 'Buscás productos o los cargás a mano (código, nombre, categoría, cantidad, costo, precio, IVA). Si cambiás el precio/costo, actualiza el producto en el catálogo.' },
      'Resumen y filtros',
      { titulo: 'Tarjetas de resumen', texto: 'Total del período, gastos, compras y pagos a proveedores.' },
      { titulo: 'Tarjetas por origen (caja/local/MP)', texto: 'Al tocarlas filtran la lista por de dónde salió el dinero.' },
      { titulo: 'Filtros de período y tipo', texto: 'Hoy / Por día / Por mes / Rango / Todo, y por tipo (gastos, compras, pagos).' },
      { titulo: 'Libro diario + acciones', texto: 'Lista todo con "Editar", "Ajustar" (en compras/pagos) y "Eliminar".' },
    ],
    tips: [
      'Cargá los gastos apenas los tenés.',
      'Elegí bien el origen del dinero para que el arqueo de caja cierre.',
    ],
    erroresComunes: [
      'Si la ganancia se ve muy alta, quizás falten gastos por cargar.',
      'No mezcles gastos personales con los del negocio.',
    ],
  },
  {
    id: 'usuarios',
    icono: '👤',
    titulo: 'Usuarios y permisos',
    resumen: 'Tu equipo y qué puede hacer cada uno.',
    color: 'from-slate-500 to-gray-700',
    gating: { rolAdmin: true },
    intro: 'Acá creás las cuentas de tu equipo (cajeros, encargados) y elegís qué puede ver y hacer cada uno. Un cajero puede vender pero no ver reportes ni configuración. Cada persona entra con su usuario y clave.',
    beneficios: [
      'Cada empleado entra con su usuario: sabés quién hizo cada venta.',
      'Le das a cada uno solo lo que necesita.',
      'Protegés la información sensible (reportes, ganancias, configuración).',
      'Desactivás a alguien sin perder su historial.',
    ],
    pasos: [
      { titulo: 'Creá un usuario', texto: 'Tocá "+ Nuevo Usuario", cargá nombre, usuario y contraseña, y elegí el rol.', imagen: '/tutoriales/usuarios-1.png' },
      { titulo: 'Definí los permisos', texto: 'Marcá a qué secciones puede entrar. Lo que no marques, no lo verá.' },
      { titulo: 'Editá o desactivá', texto: 'Con "✏️ Editar" cambiás permisos; con "🔒 Desactivar" le sacás el acceso.' },
    ],
    funciones: [
      'Arriba',
      { titulo: '"⚙️ Plantillas de permisos"', texto: 'Definís qué permisos trae cada rol (Encargado / Cajero) por defecto al crear usuarios.' },
      { titulo: '"+ Nuevo Usuario"', texto: 'Crea un usuario. En plan Estándar hay un límite (por defecto 3); Premium no tiene límite práctico.' },
      { titulo: 'Tarjetas de roles', texto: 'Admin (acceso total), Encargado y Cajero. Al tocar Encargado/Cajero editás su plantilla.' },
      'En cada usuario',
      { titulo: '"✏️ Editar"', texto: 'Cambia datos, contraseña, rol y permisos.' },
      { titulo: '"🔒 Desactivar"', texto: 'Le saca el acceso sin borrar datos (reversible).' },
      { titulo: '"🗑️ Eliminar"', texto: 'Borra el usuario para siempre (doble confirmación).' },
      'Ventana Nuevo / Editar usuario',
      { titulo: 'Nombre, usuario, email, contraseña', texto: 'El usuario se usa para entrar (sin espacios). Al editar, dejá la contraseña vacía para no cambiarla.' },
      { titulo: 'Rol y "⚡ Plantillas rápidas"', texto: 'Elegí Admin/Encargado/Cajero. Los botones "👔 Encargado" y "🧑‍💼 Cajero" cargan un set de permisos de una.' },
      { titulo: 'Permisos por panel', texto: 'Marcás qué puede hacer en cada módulo (ver, crear, editar, eliminar, vender, etc.). "Todos"/"Ninguno" marcan/desmarcan todo. Sin permisos, solo puede usar el POS.' },
      { titulo: 'Nota importante', texto: 'Usuarios y Configuración quedan siempre solo para administradores.' },
    ],
    tips: [
      'Dale a cada persona lo justo y necesario.',
      'Que cada uno tenga su propia clave: así el historial dice la verdad.',
    ],
    erroresComunes: [
      'Si un empleado no ve una sección, revisá sus permisos acá.',
    ],
  },
  {
    id: 'configuracion',
    icono: '⚙️',
    titulo: 'Configuración',
    resumen: 'Ajustar el sistema a tu negocio.',
    color: 'from-gray-500 to-slate-700',
    gating: { rolAdmin: true },
    intro: 'En Configuración dejás el sistema con la cara de tu negocio y ajustás cómo funciona. Tiene pestañas: Negocio, Configuraciones, Sistema y (en Premium) Facturación. Cada pestaña tiene su propio botón "💾 Guardar".',
    beneficios: [
      'Personalizás nombre, logo, color y tema del sistema.',
      'Activás opciones según cómo trabajás (vender sin stock, recargos, redondeo, etc.).',
      'Elegís qué medios de pago aparecen en el POS.',
      'Configurás impresión de tickets y la facturación electrónica.',
    ],
    pasos: [
      { titulo: 'Cargá los datos del negocio', texto: 'Pestaña "🏪 Negocio": nombre, CUIT, teléfono, dirección, color y modo oscuro.', imagen: '/tutoriales/configuracion-1.png' },
      { titulo: 'Ajustá cómo vendés', texto: 'Pestaña "⚙️ Configuraciones": vender sin stock, recargos, descuentos, redondeo, medios de pago, impresión.' },
      { titulo: 'Guardá', texto: 'Cada pestaña se guarda con su botón "💾 Guardar".' },
    ],
    funciones: [
      'Pestaña "🏪 Negocio"',
      { titulo: 'Datos del negocio', texto: 'Nombre, CUIT, teléfono, email y dirección (aparecen en tickets).' },
      { titulo: '"🎨 Color principal"', texto: 'Elegís el color del sistema (con paleta rápida). Se ve al instante.' },
      { titulo: '"🌙 Modo oscuro en el POS"', texto: 'Pone el punto de venta con fondo oscuro.' },
      'Pestaña "⚙️ Configuraciones"',
      { titulo: '"Vender sin stock"', texto: 'Permite vender aunque no haya stock; el stock nunca queda negativo.' },
      { titulo: '"Venta Rápida" y "Precio Mayorista"', texto: 'Habilitan vender sin inventario y usar precio mayorista (con cantidad mínima).' },
      { titulo: '"Validar Monto en Efectivo"', texto: 'Exige que lo entregado sea igual o mayor al total.' },
      { titulo: '"Mostrar stock en POS"', texto: 'Muestra la cantidad disponible en cada producto al vender.' },
      { titulo: 'Cierre de caja protegido (PIN)', texto: 'Oculta los datos del cierre hasta poner un PIN.' },
      { titulo: 'Impresión de tickets', texto: 'Automática, vista previa o no imprimir; y el tamaño de papel (58/80 mm o personalizado).' },
      { titulo: 'Recargo en tarjeta y aviso de monto alto', texto: 'Porcentaje que se suma al pagar con tarjeta, y aviso al cobrar un monto virtual grande (anti error).' },
      { titulo: 'Recargo general y descuentos', texto: 'Configurás el % de recargo y el descuento máximo que se usan en el POS.' },
      { titulo: '"Redondeo de venta"', texto: 'Botones para redondear el total al múltiplo que elijas ($10/$50/$100/$500).' },
      { titulo: 'Métodos de pago activos', texto: 'Elegís cuáles aparecen en el POS (Efectivo siempre; Tarjeta, MP, Transferencia opcionales).' },
      'Pestaña "🖥️ Sistema"',
      { titulo: 'Info y mensaje del ticket', texto: 'Versión, plan, y el mensaje al pie del ticket (ej. "¡Gracias por su compra!").' },
      { titulo: 'Zona de peligro', texto: '"Reiniciar ajustes" (vuelve la config por defecto) y "🗑️ Reiniciar datos" (borrado selectivo e irreversible, hay que escribir "ELIMINAR").' },
      'Pestaña "🧾 Facturación" (Premium)',
      { titulo: 'Facturación Electrónica', texto: 'Toda la configuración de AFIP/ARCA (ver el tutorial de Facturación).' },
    ],
    tips: [
      'Cargar logo y color hace que el sistema y los tickets se vean tuyos.',
      'Configurá bien los medios de pago para que en el POS aparezcan solo los que usás.',
    ],
    erroresComunes: [
      'Si un cambio no se ve, recargá la página.',
      'Acordate de tocar "💾 Guardar" en cada pestaña.',
    ],
  },
  {
    id: 'facturacion',
    icono: '🧾',
    titulo: 'Facturación Electrónica',
    resumen: 'Hacer facturas oficiales de AFIP/ARCA.',
    color: 'from-blue-500 to-indigo-600',
    gating: { rolAdmin: true },
    pro: true,
    intro: 'La facturación electrónica te deja hacer facturas oficiales (con CAE de AFIP/ARCA). Se configura una vez, en Configuración, y después facturás desde el POS. Tiene pestañas: Tutorial, Configuración, Certificados y Comprobantes.',
    beneficios: [
      'Hacés facturas legales sin usar otra página ni programa.',
      'La factura sale en el mismo momento de la venta.',
      'Tenés todos los comprobantes guardados y ordenados.',
      'Con "conexión rápida" arrancás sin generar tu propio certificado.',
      'Sirve para monotributistas (Factura C) y responsables inscriptos (A/B).',
    ],
    pasos: [
      { titulo: 'Activá la facturación', texto: 'En la pestaña "⚙️ Configuración", prendé el interruptor "Activar Facturación Electrónica".' },
      { titulo: 'Elegí el modo de conexión', texto: 'En "🔐 Certificados": "🚀 Conexión rápida" (la fácil) o "🔐 Certificado propio" (avanzada).' },
      { titulo: 'Cargá tus datos fiscales', texto: 'CUIT, punto de venta, régimen (monotributo/RI) y entorno (producción para facturar en serio).' },
      { titulo: 'Probá la conexión', texto: 'Tocá "🔗 Probar Conexión": si sale verde, ya podés facturar desde el POS.' },
    ],
    funciones: [
      'Pestaña "📚 Tutorial"',
      { titulo: 'Guía de 7 pasos + preguntas frecuentes', texto: 'Explica todo el trámite en ARCA. Incluye el botón "Abrir portal de ARCA →".' },
      'Pestaña "⚙️ Configuración"',
      { titulo: 'Interruptor "Activar Facturación"', texto: 'Enciende el módulo (se guarda solo). El resto de opciones aparece cuando está encendido.' },
      { titulo: 'Régimen fiscal', texto: '"Responsable Inscripto" (Factura A/B) o "Monotributista" (Factura C).' },
      { titulo: 'Datos fiscales del emisor', texto: 'Condición frente al IVA, Ingresos Brutos e inicio de actividades (van en el comprobante).' },
      { titulo: 'Punto de Venta ARCA', texto: 'El número de punto de venta habilitado en AFIP para Web Services.' },
      { titulo: 'Entorno "🧪 Homologación / 🚀 Producción"', texto: 'Pruebas (sin valor fiscal) o real. Para facturar de verdad, Producción.' },
      { titulo: '"🔗 Probar Conexión"', texto: 'Verifica que ARCA acepte tu configuración antes de facturar.' },
      { titulo: '"💾 Guardar"', texto: 'Guarda régimen, punto de venta, entorno y datos fiscales.' },
      'Pestaña "🔐 Certificados"',
      { titulo: 'Estado de la conexión', texto: 'Muestra si estás con conexión rápida, con certificado propio (vigente/vencido), o sin configurar.' },
      { titulo: '"🚀 Conexión rápida" (recomendada)', texto: 'Sin certificados: autorizás el servicio a gestionq24 desde tu clave fiscal. Cargás tu CUIT, punto de venta y régimen, y activás.' },
      { titulo: '"🔐 Certificado propio" (avanzada)', texto: 'Generás la clave y el .csr acá, subís el .csr a ARCA, y después subís el .crt que te devuelven.' },
      'Pestaña "📄 Comprobantes"',
      { titulo: 'Tipos disponibles', texto: 'Los comprobantes que podés emitir según tu régimen.' },
      { titulo: '"🧪 Emitir de prueba"', texto: 'Emitís un comprobante de prueba para verificar que todo funciona (muestra el CAE).' },
      { titulo: '"📊 Historial de Comprobantes"', texto: 'Todos los comprobantes emitidos con fecha, tipo, número, CAE, total y estado.' },
    ],
    tips: [
      'Con "conexión rápida" no necesitás generar tu propio certificado.',
      'El paso que muchos olvidan: autorizar el web service "Facturación Electrónica" al certificado en ARCA.',
      'El punto de venta debe ser del tipo "Web Services", no el de "Comprobantes en línea".',
    ],
    erroresComunes: [
      'Si ARCA rechaza, suele ser por el certificado/CUIT, por no autorizar el web service, o por el punto de venta.',
      'La fecha de la factura no puede ser anterior a la de la última que hiciste en ese punto de venta.',
      '"Homologación" no tiene valor fiscal: para facturar en serio, pasá a "Producción".',
    ],
  },
  {
    id: 'resumen-fiscal',
    icono: '🧮',
    titulo: 'Resumen Fiscal',
    resumen: 'Tu IVA y libros, mes a mes.',
    color: 'from-emerald-500 to-teal-700',
    gating: { permiso: 'resumen_fiscal' },
    pro: true,
    intro: 'El Resumen Fiscal junta lo que facturaste (ventas) y lo que compraste con factura, y calcula tu posición de IVA del mes. Ideal para controlar el monotributo o para pasarle los libros a tu contador.',
    beneficios: [
      'Ves de una tu IVA del mes (a pagar o a favor).',
      'Controlás los topes del monotributo sin sorpresas.',
      'Le facilitás el trabajo al contador (Libro IVA listo).',
      'Exportás todo a Excel.',
    ],
    pasos: [
      { titulo: 'Elegí el mes', texto: 'Con las flechas ‹ › te movés entre meses (no deja ir al futuro).', imagen: '/tutoriales/resumen-fiscal-1.png' },
      { titulo: 'Mirá tu posición de IVA', texto: 'Las tarjetas muestran total facturado, compras con factura y el IVA a pagar o a favor.' },
      { titulo: 'Exportá', texto: 'Con "⬇️ Exportar Excel" bajás el Libro IVA Ventas y Compras del mes.' },
    ],
    funciones: [
      'Arriba',
      { titulo: '"⬇️ Exportar Excel"', texto: 'Descarga el Libro IVA Ventas y Compras del mes en un Excel de dos hojas.' },
      { titulo: 'Selector de mes "‹ ... ›"', texto: 'Te movés entre meses. "›" se desactiva en el mes actual (no hay futuro).' },
      'Tarjetas de resumen',
      { titulo: '"Total Facturado (Ventas)"', texto: 'Suma de tus ventas electrónicas del mes, con el IVA débito.' },
      { titulo: '"Total Compras con Factura"', texto: 'Compras con factura del mes, con el IVA crédito.' },
      { titulo: '"Posición IVA Mensual"', texto: 'El resultado: "A pagar" si el débito supera al crédito, o "A favor" si es al revés.' },
      'Detalle',
      { titulo: '"📗 Libro IVA Ventas"', texto: 'Tabla de las ventas facturadas: fecha, tipo, número, cliente, neto, IVA y total.' },
      { titulo: '"📘 Libro IVA Compras"', texto: 'Tabla de las compras con factura (se cargan desde Gastos → Nueva Compra).' },
    ],
    tips: [
      'Miralo cada mes para controlar el acumulado del año.',
    ],
    erroresComunes: [
      'Toma solo lo facturado electrónicamente y las compras con factura; las ventas/compras sin factura no cuentan acá.',
    ],
  },
  {
    id: 'prediccion-compras',
    icono: '🛒',
    titulo: 'Predicción de compras',
    resumen: 'Cuánto comprar para no quedarte sin nada.',
    color: 'from-orange-500 to-amber-600',
    gating: { funcion: 'prediccion_compras' },
    pro: true,
    intro: 'La Predicción de compras te dice cuánto comprar de cada producto para reponer lo que se vende, mirando el día de la semana. Si mañana es sábado, mira cómo te fue los sábados. Se basa en lo vendido, no en el stock.',
    beneficios: [
      'Comprás lo justo: ni te quedás sin nada, ni te llenás de stock parado.',
      'Se basa en lo que realmente se vende.',
      'Tiene en cuenta el día de la semana.',
      'Te arma la lista y la exportás para el proveedor.',
      'Le suma un colchón de seguridad para los días fuertes.',
    ],
    pasos: [
      { titulo: 'Elegí qué cubrir', texto: 'Mañana, próximos 3 o 7 días, y cuántas semanas de historial analizar.', imagen: '/tutoriales/prediccion-1.png' },
      { titulo: 'Mirá la sugerencia', texto: 'La tabla muestra cuánto se vende ese día y cuánto comprar (columna "Comprar").' },
      { titulo: 'Llevate la lista', texto: 'Exportá a Excel o PDF para el proveedor.' },
    ],
    funciones: [
      'Controles',
      { titulo: '"Comprar para"', texto: 'Mañana, próximos 3 días o próximos 7 días.' },
      { titulo: '"Cobertura (colchón)"', texto: 'Normal / Alto / Muy alto: cuánto margen de seguridad se agrega (más alto = comprás de más para no quedarte sin stock).' },
      { titulo: '"Analizar últimas" (semanas)', texto: 'Cuánto historial mira (4, 6, 8, 12 o 16 semanas).' },
      { titulo: 'Categoría', texto: 'Todas o una categoría específica.' },
      { titulo: '"Descontar mi stock actual"', texto: 'Resta lo que ya tenés a lo que hay que comprar (usalo solo si tenés el stock al día).' },
      { titulo: '"Ocultar los que no hay que comprar"', texto: 'Esconde los productos con cantidad a comprar 0.' },
      'Resultados',
      { titulo: 'Tarjetas de resumen', texto: 'Para qué período, cuántos productos reponer y el costo estimado de la compra.' },
      { titulo: 'Tabla', texto: 'Por producto: cuánto se vende ese día, la demanda prevista, "Comprar" (la sugerencia, en verde), el costo estimado y el stock actual.' },
      { titulo: '"📤 Excel" / "📄 PDF"', texto: 'Descargan la lista de compras sugerida.' },
    ],
    tips: [
      'Cuanto más historial tengas, más precisa es la sugerencia.',
      'Es una guía: ajustala si sabés que viene un día especial.',
    ],
    erroresComunes: [
      'Con poco historial aparece "pocos datos" (baja confianza): la sugerencia es más aproximada.',
    ],
  },
  {
    id: 'multinegocio',
    icono: '🔁',
    titulo: 'Movimiento de mercadería',
    resumen: 'Mover stock entre tus locales.',
    color: 'from-purple-500 to-fuchsia-600',
    gating: { funcion: 'multinegocio' },
    pro: true,
    intro: 'Si tenés más de un local conectado, movés mercadería de uno a otro: uno envía, el otro recibe y confirma lo que llegó, y el stock se ajusta solo en los dos lados. Con remito, como en las empresas grandes.',
    beneficios: [
      'Movés stock entre locales sin planillas ni llamados.',
      'El que recibe confirma qué llegó: no se pierde stock.',
      'El stock se actualiza solo en los dos negocios.',
      'Queda todo registrado: quién envió, quién recibió y cuándo.',
      'Imprimís el remito para el traslado.',
    ],
    pasos: [
      { titulo: 'Enviá la mercadería', texto: 'Desde el POS (Movimientos), elegí el local destino, agregá productos y cantidades, y confirmá. Queda "en proceso".', imagen: '/tutoriales/multinegocio-1.png' },
      { titulo: 'Recibí en el otro local', texto: 'En "Movimiento de mercadería", el destino tilda lo que llegó y confirma. Ahí se mueve el stock.', imagen: '/tutoriales/multinegocio-2.png' },
      { titulo: 'Seguí el historial', texto: 'Cada movimiento muestra su estado, quién lo hizo y permite reimprimir el remito.' },
    ],
    funciones: [
      'Filtros y resumen',
      { titulo: 'Buscador, período y tipo', texto: 'Buscás por producto y filtrás por fechas (Hoy/7 días/Este mes/Mes pasado), tipo (Enviados/Recibidos), estado y negocio.' },
      { titulo: 'Aviso de pendientes', texto: 'Te avisa si tenés envíos esperando que confirmes la recepción.' },
      { titulo: 'Tarjetas de resumen', texto: 'Cantidad de movimientos, valor enviado, valor recibido e ítems movidos.' },
      { titulo: 'Sub-pestañas', texto: '"📋 Historial" y "📦 Productos movidos" (con exportar Excel/PDF).' },
      'En cada movimiento',
      { titulo: 'Estado', texto: 'En proceso, Recibido, Recibido parcial, Rechazado o Anulado.' },
      { titulo: 'Detalle (flecha ▶)', texto: 'Muestra los productos con lo que llegó/faltó, y quién envió y recibió.' },
      { titulo: '"✅ Confirmar recepción"', texto: 'Lo ve quien recibe: tildás lo que llegó (lo no tildado queda como faltante y no suma stock) y confirmás.' },
      { titulo: '"✏️ Editar envío"', texto: 'Solo el que envió (admin) y mientras está "en proceso": agrega/quita productos o cambia cantidades.' },
      { titulo: '"🖨️ Remito"', texto: 'Reimprime el remito del movimiento.' },
      { titulo: 'Anular / Cancelar / Rechazar', texto: 'Solo admin. Si ya se había recibido, revierte el stock en ambos negocios.' },
    ],
    tips: [
      'Lo que se envía no se descuenta hasta que el otro confirma qué recibió.',
      'Imprimí el remito para controlar la mercadería al llegar.',
    ],
    erroresComunes: [
      'Si el stock no se movió, es porque el envío sigue "en proceso" (falta que el destino lo reciba).',
    ],
  },
];
